config/routes.rb
Rails.application.routes.draw do
  resources :users do
    resources :products
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :products
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @user = User.find(params[:user_id])
    @products = @user.products
  end

  # GET /products/1
  # GET /products/1.json
  def show
    user = User.find(params[:user_id])
    @product = user.products.find(params[:id])
  end

  # GET /products/new
  def new
    user = User.find(params[:user_id])
    @product = user.products.new
  end

  # GET /products/1/edit
  def edit
    user = User.find(params[:user_id])
    @product = user.products.find(params[:id])
  end

  # POST /products
  # POST /products.json
  def create
    user = User.find(params[:user_id])
    @product = user.products.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to [@product.user, @product], notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    user = User.find(params[:user_id])
    @product = user.products.find(params[:id])
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to [@product.user, @product], notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    user = User.find(params[:user_id])
    @product = user.products.find(params[:id])
    @product.destroy
    respond_to do |format|
      format.html { redirect_to user_products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :weight, :price, :user_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :username, :is_admin)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Lab08</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <nav class="navbar navbar-inverse">
    <div class="container-fluid">
      <div class="navbar-header">
        <a class="navbar-brand" href="#">Inventory Management</a>
      </div>
      <ul class="nav navbar-nav">
        <li><%= link_to "Users", users_path%></li>
      </ul>
    </div>
  </nav>
    <%= yield %>
  </body>
</html>

app/views/products/_form.html.erb
<%= form_for([@product.user, @product]) do |form| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :product_name %>
  </div>

  <div class="field">
    <%= form.label :weight %>
    <%= form.number_field :weight, id: :product_weight %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.number_field :price, id: :product_price %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', [@product.user, @product] %> |
<%= link_to 'Back', user_products_path(@product.user) %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Products</h1>

<div class="container">
  <table class="table table-bordered">
    <thead>
    <tr>
      <th>Name</th>
      <th>Weight</th>
      <th>Price</th>
      <th colspan="3">Options</th>
    </tr>
    </thead>

    <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.weight %></td>
        <td><%= product.price %></td>
        <td><%= link_to 'Show', [product.user, product] %></td>
        <td><%= link_to 'Edit', edit_user_product_path(product.user, product) %></td>
        <td><%= link_to 'Destroy', [product.user, product], method: :delete, data: {confirm: 'Are you sure?'} %></td>
      </tr>
    <% end %>
    </tbody>
  </table>

  <%= link_to 'New Product', new_user_product_path %>
  <%= link_to 'Back', user_path(@user) %>

</div>

app/views/products/new.html.erb
<div class="col-md-offset-4">

  <h1>New Product</h1>

  <%= render 'form'%>

  <%= link_to 'Back', user_products_path(@product.user) %>
</div>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Weight:</strong>
  <%= @product.weight %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<%= link_to 'Edit', edit_user_product_path(@product.user, @product) %> |
<%= link_to 'Back', user_products_path(@product.user) %>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name, id: :user_first_name %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name, id: :user_last_name %>
  </div>

  <div class="field">
    <%= form.label :username %>
    <%= form.text_field :username, id: :user_username %>
  </div>

  <div class="field">
    <%= form.label :is_admin %>
    <%= form.check_box :is_admin, id: :user_is_admin %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>


<div class="container">
  <table class="table table-bordered">
    <thead>
      <tr>
        <th>First name</th>
        <th>Last name</th>
        <th>Username</th>
        <th>Is admin</th>
        <th colspan="3"> Options</th>
      </tr>
    </thead>

    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= user.first_name %></td>
          <td><%= user.last_name %></td>
          <td><%= user.username %></td>
          <td>
            <% if user.is_admin %>
              Yes
            <% else %>
              No
            <% end %>
          </td>
          <td><%= link_to 'View user profile', user %></td>
          <td><%= link_to 'Edit', edit_user_path(user) %></td>
          <td><%= link_to 'Eliminate User', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <%= link_to 'Create user', new_user_path %>
</div>

app/views/users/new.html.erb
<div class="col-md-offset-4">

<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

</div>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<div class="col-md-3">
  <% if (@user.is_admin)%>
  <% end %>
</div>
<div class="col-md-offset-4">
  <h1>
    <strong>
      <%= @user.first_name %>
      <%= @user.last_name %>
    </strong>
  </h1>
  <p>
    <strong>Username:</strong>
    <%= @user.username %>
  </p>

  <p>
    <% if (@user.is_admin)%>

    <strong>Is admin of the page</strong>
    <% end %>
  </p>
  <%= link_to 'Products', user_products_path(@user) %>
  <%= link_to 'Edit', edit_user_path(@user) %> |
  <%= link_to 'Back', users_path %>
</div>